services:
  go-app:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    container_name: go-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - go-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
